app/(dashboard)/(routes)/image/page.tsx, app/api/image/route.ts, prisma/migrations/20241116120133_image/migration.sql, prisma/schema.prisma, public/ShareIcon.svg
fixes issue #3 
enhanced card ui plus solved some minor bugs, like handling data obtained form api/image
=> feat:image-card-imporved-ui

app/(dashboard)/(routes)/settings/page.tsx, app/(dashboard)/(routes)/user-profile/[[...user-profile]]/page.tsx, middleware.ts, package-lock.json, package.json
=> feat:add logout and account manage in settings

app/(dashboard)/(routes)/code/page.tsx
=> fix code div overflow on small devices

app/(dashboard)/(routes)/conversation/page.tsx
=> feat add markdown in conversation page

components/sidebar.tsx
=> add pro badge for pro users

app/(landing)/page.tsx, app/layout.tsx, package-lock.json, package.json
fixes #8 
already all button have laoding where ever required, laoding was required while navigating which is added
=> add loading bar when navigating

app/(dashboard)/(routes)/image/page.tsx, app/api/image/delete/route.ts, components/loadingSpinner.tsx, packages/features/deleteImage.ts, prisma/schema.prisma
=> add delete image button and functionality

components/ui/sheet.tsx
=> fix(#36): missing close icon on light theme

app/(dashboard)/(routes)/chat/page.tsx, package-lock.json, package.json, tailwind.config.ts
=> add styled scrollbar when too many chats in chat page

app/(dashboard)/(routes)/image/page.tsx, components/loadingSpinner.tsx, components/moving-border.tsx, tailwind.config.ts
=> add surprise me button 

app/(dashboard)/(routes)/image/page.tsx
=> fix error handling in surprise me button

app/(dashboard)/(routes)/image/page.tsx
=> fix image delete issue

app/(dashboard)/(routes)/image/page.tsx, app/(dashboard)/(routes)/marketplace/page.tsx, components/CopyButton.tsx, packages/features/copyToClipboard.ts, packages/features/index.ts
=> feat: copy button in images and marketplace page

app/(dashboard)/(routes)/image/page.tsx
=> fix: prev images delete issue

app/(dashboard)/(routes)/image/page.tsx, app/(landing)/page.tsx, components/background-beams.tsx, components/landing-chat-section.tsx, components/landing-code-section.tsx, components/landing-hero.tsx, tailwind.config.ts
=> feat: enhance mobile landing page

app/api/image/get-user-images/route.ts
=> fix: prev images were shown in ascending order

components/team-switcher.tsx
=> curious logo sidebar redirect resolved

Dockerfile, README.md, docker-compose.yml
Do merge it, as  I had gone carefully and made the relevent chagnes in prisma and somewhere else requried, which you can surely confirm from your side.
One error I have figured out and it seems from the side of next itself as gone through several community post online.
=> Docker Optimised

app/(dashboard)/(routes)/image/page.tsx, components/loadingSpinner.tsx
=> fix: loader color during theme change

app/(dashboard)/(routes)/image/page.tsx
=> fix create button hover effect

components/mobile-sidebar.tsx
=> feat sidebar close on click on any item

components/infinite-moving-card.tsx
=> stop hover card pause

components/landingNavbar.tsx, components/themes.tsx
I believe users would prefer automatic theme toggling over the dropdown menu, so I implemented it here. Please review and make changes as necessary
I also removed the 'System Theme' option, which is kinda redundant.
Here's the recording for the output:
https://github.com/user-attachments/assets/ff03b1ce-8618-4ef8-a827-84b8a62686e4
=> Improved theme toggle

app/not-found.tsx, components/PageNotFound.tsx, components/landing-bottom.tsx
* Added 404 "Page Not Found" page
* Improved the footer design that align with both themes
Output:
https://github.com/user-attachments/assets/d57f45aa-84a5-490f-9f78-b1bc8fee1c77
=> New design

app/(dashboard)/(routes)/image/page.tsx
=> fix:on enter prompt not submits on image page

app/(dashboard)/(routes)/chat/page.tsx, components/ui/button.tsx
=> Redesign chat page

next.config.mjs
=> removed next image optimization

app/(dashboard)/(routes)/image/page.tsx
=> fix button size for small devices

app/(dashboard)/(routes)/chat/page.tsx, app/(dashboard)/(routes)/code/page.tsx, app/api/code/route.ts
removed json from llm response and add tags approach, this would help to implement streaming of data feature.
=> Remove json llm response

app/(dashboard)/(routes)/dashboard/page.tsx
=> enhanced dashboard
